[project]
name = 'Decentralized-Specialized-Equipment-Leasing-for-Film-Production'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.insurance-verification]
path = 'contracts/insurance-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-verification]
path = 'contracts/production-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-agreement]
path = 'contracts/rental-agreement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
